//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2021-2022 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
//
//===----------------------------------------------------------------------===//

import Foundation

enum Stats {}

extension Stats {
  // Maximum allowed standard deviation is 7.5% of the median runtime
  static let maxAllowedStdev = 0.15

  /// Two-tailed 95% critical values of the Student's t-distribution,
  /// indexed by degrees of freedom.
  private static let tCriticalTable: [(df: Double, value: Double)] = [
    (1, 12.706), (2, 4.303), (3, 3.182), (4, 2.776), (5, 2.571),
    (6, 2.447), (7, 2.365), (8, 2.306), (9, 2.262), (10, 2.228),
    (12, 2.179), (15, 2.131), (20, 2.086), (25, 2.060), (30, 2.042),
    (40, 2.021), (60, 2.000), (120, 1.980), (.infinity, 1.960),
  ]

  /// The critical value for a two-tailed test at 95% confidence with the
  /// given degrees of freedom, interpolating between table entries.
  ///
  /// Interpolates on `1/df` rather than `df` directly, since the
  /// critical value approaches its asymptote (1.96) roughly as `1/df`,
  /// so this tracks the true curve much more closely than a linear
  /// interpolation in `df` would between widely-spaced entries.
  static func tCritical(df: Double) -> Double {
    let df = max(df, 1)
    var lower = tCriticalTable[0]
    for entry in tCriticalTable {
      if entry.df >= df {
        guard entry.df != lower.df else { return entry.value }
        let x = 1 / df, x0 = 1 / lower.df
        let x1 = entry.df.isFinite ? 1 / entry.df : 0
        let t = x1 == x0 ? 0 : (x - x0) / (x1 - x0)
        return lower.value + t * (entry.value - lower.value)
      }
      lower = entry
    }
    return tCriticalTable.last!.value
  }

  /// Returns the result of Welch's t-test for significance, as a fallback
  /// for comparisons with result files generated by older versions.
  static func tTest(_ a: Measurement, _ b: Measurement) -> Bool {
    let n1 = Double(a.samples)
    let n2 = Double(b.samples)
    let v1 = pow(a.stdev, 2) / n1
    let v2 = pow(b.stdev, 2) / n2
    guard v1 + v2 > 0 else {
      // Both sides measured exactly zero spread: treat any difference at
      // all as significant rather than dividing by zero.
      return a.median != b.median
    }
    let tVal = (a.median.seconds - b.median.seconds) / (v1 + v2).squareRoot()
    // Welch–Satterthwaite equation for effective degrees of freedom.
    let df = pow(v1 + v2, 2) / (pow(v1, 2) / (n1 - 1) + pow(v2, 2) / (n2 - 1))
    return abs(tVal) > tCritical(df: df)
  }

  /// Returns the result of Mann–Whitney U test for significance.
  static func mannWhitneyTest(_ a: [Time], _ b: [Time]) -> Bool {
    guard !a.isEmpty, !b.isEmpty else { return false }

    // Rank the pooled samples, giving tied values their average rank.
    let pooled = (a.map { (time: $0, group: 0) } + b.map { (time: $0, group: 1) })
      .sorted { $0.time < $1.time }
    var rankSum = [0.0, 0.0]
    var tieCorrection = 0.0
    var i = 0
    while i < pooled.count {
      let j = pooled[i...].firstIndex(where: { $0.time != pooled[i].time }) ?? pooled.count
      let averageRank = Double(i + j + 1) / 2  // rank is one-based, so this will be 1 if unique
      for k in i..<j { rankSum[pooled[k].group] += averageRank }
      let tieSize = Double(j - i)
      if tieSize > 1 { tieCorrection += tieSize * tieSize * tieSize - tieSize }
      i = j
    }

    let n = Double(a.count), m = Double(b.count), total = n + m
    let u1 = rankSum[0] - n * (n + 1) / 2
    let meanU = n * m / 2
    let varianceU = n * m / 12
      * ((total + 1) - tieCorrection / (total * (total - 1)))
    guard varianceU > 0 else { return u1 != meanU }
    // Continuity correction: U is discrete, the normal approximation is
    // continuous, so pull the numerator half a step toward zero.
    let continuity = 0.5 * (u1 > meanU ? -1.0 : (u1 < meanU ? 1.0 : 0.0))
    let z = (u1 - meanU + continuity) / varianceU.squareRoot()
    return abs(z) > 1.96
  }
}

extension BenchmarkResult.Comparison {
  static func isSignificantlyDifferent(_ a: Measurement, _ b: Measurement) -> Bool {
    if let aSamples = a.rawSamples, let bSamples = b.rawSamples {
      return Stats.mannWhitneyTest(aSamples, bSamples)
    }
    return Stats.tTest(a, b)
  }
}

extension BenchmarkResult {
  var runtimeIsTooVariant: Bool {
    runtime.stdev > Stats.maxAllowedStdev * runtime.median.seconds
  }
}
