//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2021 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
//
//===----------------------------------------------------------------------===//

// This was auto-generated by utils/gen-unicode-data/GenScalarProps,
// please do not edit this file yourself!

#ifndef SCALAR_PROP_DATA_H
#define SCALAR_PROP_DATA_H

#include "../SwiftShims/SwiftStdint.h"

