//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2021-2022 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
//
//===----------------------------------------------------------------------===//

// This file has lines generated by createBenchmark.py
// Do not remove the start of registration or end of registration markers

extension BenchmarkRunner {
  mutating func registerDefault() {
    // -- start of registrations --
    self.addReluctantQuant()
    self.addCSS()
    self.addNotFound()
    self.addGraphemeBreak()
    self.addHangulSyllable()
    // self.addHTML() // Disabled due to \b being unusably slow
    self.addEmail()
    self.addCustomCharacterClasses()
    self.addBuiltinCC()
    self.addUnicode()
    self.addLiteralSearch()
    self.addDiceNotation()
    self.addErrorMessages()
    self.addIpAddress()

    self.addURLWithWordBoundaries()
    self.addFSPathsRegex()

    // Register community benchmarks
    self.addCommunityBenchmark_sspringerURL()

    // -- end of registrations --
  }
}
